apiVersion: apps/v1
kind: Deployment
metadata:
  name: levelmix-web
  namespace: levelmix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: levelmix-web
  template:
    metadata:
      labels:
        app: levelmix-web
    spec:
      containers:
      - name: web
        image: gcr.io/YOUR_PROJECT_ID/levelmix-web:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: levelmix-config
        - secretRef:
            name: levelmix-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: levelmix-web-service
  namespace: levelmix
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: levelmix-web
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: levelmix-web-hpa
  namespace: levelmix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: levelmix-web
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80